import React from 'react';
import Carousel from '@/comps/carousel';
import styles from '@/styles/Project.module.css';
import Navbar from '@/comps/navbar';
import Head from 'next/head';
import Footer from '@/comps/footer';

const Project = () => {
  const projectImages = [
    'itt1.png',
    'itt2.png',
    'itt3.png',
    'itt4.png',
    'itt5.png',
  ];

  return (
    <>
    <Head>
      <title>Marisa Lenarduzzi</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/logo.ico" />
    </Head>
    <main className={styles.main}> 
    <Navbar/>
    <div className={styles.project}>   
      <div className={styles.projectHeader}>
        <h1 className={styles.projectTitle}>In the Trees E-mag</h1>
        <p className={styles.projectDate}>Date: November 2022</p>
      </div>
      <Carousel images={projectImages} />
      <div className={styles.projectDescription}>
        <h2>Description</h2>
        <p>This eight page magazine spread was created to spread awareness about the future of sustainable living and the important role treehouses could play. Photoshop, Indesign and Illustrator were used to create the components for this E-magazine. </p>
      </div>
      <div className={styles.projectInfo}>
        <div className={styles.projectInfoItem}>
          <h3>Tools Used</h3>
          <ul>
            <li>Photoshop</li>
            <li>Illustrator</li>
            <li>InDesign</li>
          </ul>
        </div>
        <div className={styles.projectInfoItem}>
          <h3>Roles</h3>
          <ul>
            <li>Visual Design</li>
            <li>Graphic Design</li>
            <li>Magazine Design</li>
          </ul>
        </div>
      </div>
    </div>
    <Footer />
    </main>
    </>
  );
};

export default Project;
