import React from 'react';
import Carousel from '@/comps/carousel';
import styles from '@/styles/Project.module.css';
import Navbar from '@/comps/navbar';
import Head from 'next/head';
import Footer from '@/comps/footer';

const Project = () => {
  const projectImages = [
    '2mockup.png',
    'pg1.png',
    'pg2.png',
    'pg3.png',
    'pg4.png',
    'pg5.png',
    'pg6.png',
  ];

  return (
    <>
    <Head>
      <title>Marisa Lenarduzzi</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/logo.ico" />
    </Head>
    <main className={styles.main}> 
    <Navbar/>
    <div className={styles.project}>   
      <div className={styles.projectHeader}>
        <h1 className={styles.projectTitle}>LocalScoop App</h1>
        <p className={styles.projectDate}>Date: March 2022</p>
      </div>
      <Carousel images={projectImages} />
      <div className={styles.projectDescription}>
        <h2>Description</h2>
        <p>LocalScoop is a marketplace app with the purpose of highlighting small businesses local to you. The app has a side for both customers and businesses. I created multiple pages for the customer side including the business profile page, trending page, and the feed.  </p>
      </div>
      <div className={styles.projectInfo}>
        <div className={styles.projectInfoItem}>
          <h3>Tools Used</h3>
          <ul>
            <li>Figma</li>
            <li>After Effects</li>
            <li>Illustrator</li>
            <li>Premiere</li>
          </ul>
        </div>
        <div className={styles.projectInfoItem}>
          <h3>Roles</h3>
          <ul>
            <li>UX/UI Designer</li>
          </ul>
        </div>
      </div>
    </div>
    <Footer />
    </main>
    </>
  );
};

export default Project;
