import React from 'react';
import Carousel from '@/comps/carousel';
import styles from '@/styles/Project.module.css';
import Navbar from '@/comps/navbar';
import Head from 'next/head';
import Footer from '@/comps/footer';

const Project = () => {
  const projectImages = [
    'ohanamockup.png',
    'inprogressmockup.png',
    'ohanachatmockup.png',
    'ohanaconnectmockup.png',
  ];

  return (
    <>
    <Head>
      <title>Marisa Lenarduzzi</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/logo.ico" />
    </Head>
    <main className={styles.main}> 
    <Navbar/>
    <div className={styles.project}>   
      <div className={styles.projectHeader}>
        <h1 className={styles.projectTitle}>Ohana App</h1>
        <p className={styles.projectDate}>Date: December 2022</p>
      </div>
      <Carousel images={projectImages} />
      <div className={styles.projectDescription}>
        <h2>Description</h2>
        <p>An app created for people with accessibility issues to invite people they trust to help them with daily tasks and errands. The aim of the app was to reduce guilt for caretakers and those in need, so the main challenge was to create an app that was accessible for all and non-stereotyping. </p>
      </div>
      <div className={styles.projectInfo}>
        <div className={styles.projectInfoItem}>
          <h3>Tools Used</h3>
          <ul>
            <li>Figma</li>
            <li>Photoshop</li>
            <li>Illustrator</li>
          </ul>
        </div>
        <div className={styles.projectInfoItem}>
          <h3>Roles</h3>
          <ul>
            <li>Project Manager</li>
            <li>Idea Owner</li>
            <li>UX/UI Designer</li>
          </ul>
        </div>
      </div>
    </div>
    <Footer />
    </main>
    </>
  );
};

export default Project;
